### ISSUE TITLE
Add `elixir`

### ISSUE THREAD

**Issue by arthurvr** [alferov/awesome-gulp#5]
Don't really know in what category it deserves. It's build by the laravel team and loved by their community so I think it deserves a place on the list. It's also a beautiful showcase of Gulp for non-front-end things.

https://github.com/laravel/elixir

**Comment by alferov** [comment]
Added: https://github.com/alferov/awesome-gulp/commit/eed15658503b9160f1d39447406ac9ac1e43eaac
