### ISSUE TITLE
Add some boilerplate projects

### ISSUE THREAD

**Issue by arthurvr** [alferov/awesome-gulp#7]
Should we consider adding some cool boilerplate projects using gulp to the list? That kind of projects make using gulp easier for many people.

I was thinking about things like
- [generator-gulp-webapp](http://yeoman.github.io/generator-gulp-webapp/)
- [Web Starter Kit](https://developers.google.com/web/tools/starter-kit/)
- [Polymer Starter Kit](https://developers.google.com/web/tools/polymer-starter-kit/index?hl=en)
- ...

**Comment by alferov** [comment]
Added: https://github.com/alferov/awesome-gulp/commit/ab9e6285a164b46049886b840ff36f4084853db9
