### ISSUE TITLE
contributing guidelines don't match reality

### ISSUE THREAD

**Issue by arthurvr** [alferov/awesome-gulp#8]
From the contribution guidelines:

> Use the following format: `[package](link) - Description.`

Which is not how you're currently doing it. You don't have a period after descriptions. Let's fix the list, or the `contributing.md` file.

**Comment by alferov** [comment]
Oh, my bad, thank you.
I'll fix the list, because most of the awesome lists have periods after descriptions, so it would have more unified look.

**Comment by arthurvr** [comment]
:+1:
