### ISSUE TITLE
Add gulp-lesshint

### ISSUE THREAD

**Issue by shellscape** [alferov/awesome-gulp#9]
[gulp-lesshint](https://www.npmjs.com/package/gulp-lesshint) is a plugin around the [lesshint](https://github.com/lesshint/lesshint) project. Lints both css **and** less. Poopton of configuration options, enthusiastic maintainers (disclosure: I have contributed)

**Comment by alferov** [comment]
@shellscape, I found an [issue](https://github.com/lesshint/lesshint/issues/80). I'll add lesshint once it's resolved.
Thank you for your contribution!
